# -*- coding: utf-8 -*-
"""Histogram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-W1MSHTwGdlmmf3NFFS71yaCQQaTjppo
"""

import matplotlib.pyplot as plt

data =[5,7,7,8,9,10,10,11,12,11,11]

plt.hist(data,bins=10,edgecolor='black')
plt.title('simple Histogram example')
plt.xlabel('numbers')
plt.ylabel('Count')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
datf = pd.DataFrame({"MAA":[7,4,5,6,3],
                     "ZEE":[8,12,3,5,5],
                     "Gemini":[12,2,3,4,8]})
p = sns.histplot(data=datf)
p.set(xlabel="X Label Value",ylabel = "Y Label Value")
plt.show()

import matplotlib.pyplot as plt
import numpy as np
np.random.seed(42)
dataa = np.random.randint(20,81,100)
plt.hist(dataa,bins=15,edgecolor='black')
plt.title('simple Histogram example')
plt.xlabel('numbers')
plt.ylabel('Count')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve','sunil','mani','jc','satwik','tarun','rajni'],
    'Age': [25, 30, 22, 28, 35,67,66,78,67,54,88],
}

df =pd.DataFrame(data)
plt.figure(figsize=(8,6))
sns.boxplot(x='Name',y='Age',data=df)
plt.title('Student Name: Ages')
plt.xlabel('Name')
plt.ylabel('Age')
plt.show()

